version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: app-dev
    image: leandro-wrocha/shopping-cart-app:dev
    container_name: shopping-cart-app
    ports:
      - "${APP_PORT}:9000"
    volumes:
      - ./src:/var/www:rw
      - ./.env:/var/www/.env:rw
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
    environment:
      - XDEBUG_MODE=develop,debug
      - XDEBUG_START_WITH_REQUEST=trigger
      - XDEBUG_CLIENT_HOST=host.docker.internal
      - XDEBUG_CLIENT_PORT=9003
    env_file:
      - .env
    networks:
      - default
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    image: nginx:stable-alpine
    container_name: shopping-cart-nginx
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./src:/var/www:ro
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - default
    depends_on:
      - app
  db:
    image: mysql:8.0
    container_name: shopping-cart-db
    ports:
      - "${MYSQL_PORT}:3306"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - default

volumes:
  db_data:
    driver: local

networks:
  default:
    driver: bridge
